version: "3"
services:
  redis:
    container_name: redis
    image: redis
  mysql:
    container_name: mysql
    image: mysql:5.7.30
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=fastapi-admin
    ports:
      - 3306:3306
    volumes:
      - /Users/jeong-geun-yeong/coding/fastapi-admin/mysql/data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  app:
    build: .
    restart: always
    environment:
      - DATABASE_URL=mysql://root:123456@mysql:3306/fastapi-admin
      - REDIS_URL=redis://redis:6379/0
      - AWS_ACCESS_KEY_ID=your-aws-key
      - AWS_SECRET_ACCESS_KEY=your-aws-secret
      - AWS_S3_BUCKET=social-monitoring-v2-backup
      - ELASTICSEARCH_URL=http://elasticserach/test_index/_search
      - ELASTICSEARCH_USER=your-elastic-user
      - ELASTICSEARCH_PASSWORD=your-elastic-pwd

    ports:
      - 8000:8000
    image: analyzer-server/central-data-server:1.4.1-fix
    command: uvicorn central.main:app_ --port 8000 --host 0.0.0.0
